spring.datasource.url=jdbc:postgresql://localhost:5432/shopstack_db
spring.datasource.username=postgres
spring.datasource.password=Anirban@069
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Increase request size limits for Base64 and multipart image uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-swallow-size=50MB
server.tomcat.max-http-form-post-size=50MB

# Product Image Upload Directory and Base URL
app.upload.dir=uploads/products/
app.backend.base-url=http://localhost:8080

# Razorpay Payment Gateway Configuration
razorpay.key.id=rzp_test_TOD9vXSNPzLLOn
razorpay.key.secret=w29deAvwjgp46fRzaVGc45NT
razorpay.currency=INR